name: Build OP-36 Firmware  
on: [push, pull_request, workflow_dispatch]

jobs:
  build-op36:
    uses: ergohaven/ergohaven-zmk/.github/workflows/build-user-config.yml@main
    with:
      shields: op-36_left,op-36_right
      config-files: op36.conf
